---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 5.0.1
kubeVersion: ">=1.31.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Pod spec.serviceAccountName now properly uses the resolved name (including global.nameOverride) when auto-detecting a single serviceAccount.
    - kind: fixed
      description: |-
        Allow omitting namespace in route parentRefs.
    - kind: changed
      description: |-
        Allow setting namespace field on rawResources.
